#!/bin/bash
# open cycling data editor

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

DEVELOP="${CYCLETRACKS_DEVELOP:-0}"
DEVELOP=$(($DEVELOP+0))
CURRENT_BRANCH=$(git -C $DIR branch --show-current)
if [ $DEVELOP == 0 ] && [ $CURRENT_BRANCH != "main" ]; then
    # not in develop mode, checkout main branch
    git -C $DIR checkout main
fi

python3 $DIR/main.py

if [ $DEVELOP == 0 ] && [ $CURRENT_BRANCH != "main" ]; then
    # return to branch
    git -C $DIR checkout $CURRENT_BRANCH
fi