#!/bin/bash

testDir="../cycleTracksTest"

if [ -d "$testDir" ]; then
    rm -rf $testDir/*
else
    mkdir -p $testDir
fi

cd $testDir

echo "cd $testDir"

git clone git@github.com:keziah55/cycleTracks.git

cd cycleTracks

python3 -m venv .

source bin/activate

pip -V

# test with pyside 2, then pyqt5
export QT_API=pyside2
pip install -r requirements.txt
pip install pytest pytest-qt pytest-cov pytest-profiling
./run_tests

export QT_API=pyqt5
pip install -r requirements.txt
pip install pytest pytest-qt pytest-cov pytest-profiling
./run_tests

deactivate