#!/bin/bash

testDir="../cycleTracksTest"

if [ -d "$DIRECTORY" ]; then
    rm -rf $testDir/
else
    mkdir -p $testDir
fi

cd $testDir

git clone git@github.com:keziah55/cycleTracks.git

python3 -m venv .

source bin/activate



deactivate